### ISSUE TITLE
sscan is not implemented

### ISSUE THREAD

**Issue by bjornkihlberg** [Anut-py/h-raylib#16]
[`sscan`](https://hackage.haskell.org/package/bearriver-0.14.1/docs/src/FRP.BearRiver.html#sscan) is not implemented.

I can fix it if you want but I wanted to report it here before I intrude.

**Comment by Anut-py** [comment]
I think you're in the wrong repository. You linked to a different package.

**Comment by bjornkihlberg** [comment]
@Anut-py omg lol yes, haha sorry
