### ISSUE TITLE
`clamp` function in Raylib.Util.Math can be more haskellish

### ISSUE THREAD

**Issue by futu2** [Anut-py/h-raylib#31]
Haskell-styled function should be good at combination.

e.g. [`clamp`](https://hackage.haskell.org/package/h-raylib-4.6.0.3/docs/Raylib-Util-Math.html#v:clamp)

clamp has to be used in this way
```
clamp Value_to_clamp Lower_bound Upper_bound
```
more haskellish args ord should be
```
clamp Lower_bound Upper_bound Value_to_clamp 
```
if change the order of args the endo-function will change 
from `(\x -> clamp x (-40) 40)`
to `clamp (-40) 40`
which makes this function combine easily with other `Float -> Float` function

Same thing goes: 
- [normalize](https://hackage.haskell.org/package/h-raylib-4.6.0.3/docs/Raylib-Util-Math.html#v:normalize)
- [remap](https://hackage.haskell.org/package/h-raylib-4.6.0.3/docs/Raylib-Util-Math.html#v:remap)
- [wrap](https://hackage.haskell.org/package/h-raylib-4.6.0.3/docs/Raylib-Util-Math.html#v:wrap)

**Comment by Anut-py** [comment]
Resolved by #32
