### ISSUE TITLE
Windows - GCC missing libs error

### ISSUE THREAD

**Issue by Poselsky** [Anut-py/h-raylib#36]
When I've included this package into Stack build project, I've got error : * Missing (or bad) C libraries: gcc_eh

Can we please include into documentation these steps to resolve it?

This errors occurs when haskell stack can't find gcc libs. To fix this follow these steps:

1. Run `stack exec -- pacman -Syu`, `stack exec -- pacman -S gcc`
2. Then "stack exec -- gcc -print-libgcc-file-name"
3. Copy the path without libgcc.a and paste it inside extra-lib-dirs stack.yaml

**Comment by Anut-py** [comment]
This fix is no longer necessary as of version `5.1.0.1`
