### ISSUE TITLE
defaultWindowResources is undocumented

### ISSUE THREAD

**Issue by OlegAlexander** [Anut-py/h-raylib#49]
Hello and thank you for creating these bindings!

I wanted to report that the `defaultWindowResources` function defined [here](https://hackage.haskell.org/package/h-raylib-5.1.1.0/docs/src/Raylib.Internal.html#defaultWindowResources) isn't visible in the documentation. I had to click on Source for `WindowResources` and that's how I found it.

On a related note, I'm trying to get `loadTexture` to work which requires `WindowResources`. Would you happen to have an example of using `loadTexture`? Thanks!

**Comment by OlegAlexander** [comment]
Ah, I can see in the DOCUMENTATION.md file that the `initWindow` function returns a `WindowResources`. (The DOCUMENTATION.md file is a little hard to find, so that's why I missed it.) 

However, my question about an example of using `loadTexture` still stands. Thanks!

**Comment by Anut-py** [comment]
You can look at the examples to see how to use `WindowResources`. Below is an example of how to use it with `loadTexture`.

```hs
{-# OPTIONS -Wall #-}
{-# LANGUAGE TemplateHaskell #-}
module Main where

import Raylib.Core
import Raylib.Core.Textures
import Raylib.Util
import Raylib.Util.Colors

startup :: IO WindowResources
startup = do
  window <- initWindow 600 450 "loadTexture example"
  setTargetFPS 60
  return window

mainLoop :: WindowResources -> IO WindowResources
mainLoop window = do
  drawing $ do
      clearBackground rayWhite
      loadTexture "/path/to/file" window -- this is what you're looking for
  return window

shouldClose :: WindowResources -> IO Bool
shouldClose _ = windowShouldClose

teardown :: WindowResources -> IO ()
teardown = closeWindow

raylibApplication 'startup 'mainLoop 'shouldClose 'teardown
```

**Comment by OlegAlexander** [comment]
Thank you! That's super helpful!
