### ISSUE TITLE
Remove usage of unsafeIO from getRayCollision functions

### ISSUE THREAD

**Issue by Ashe** [Anut-py/h-raylib#5]
Hello, and first of all thank you for these bindings - I've been enjoying using them!

However, I think I've found a bug. I am currently working on [a project](https://github.com/Ashe/Notakto/tree/dc5ddbca2d120be8534c922d3ca4860284e37644) and for some reason I'm getting wildly different behaviours when `getRayCollisionXXX` is involved. Here's a snippet (which you can find [here](https://github.com/Ashe/Notakto/blob/dc5ddbca2d120be8534c922d3ca4860284e37644/src/lib/Lib.hs#L97-L103))

```hs

checkBoard :: PlayerAimComponent -> (BoardComponent, PositionComponent) -> System World BoardComponent
checkBoard (Aim ray) (_, p) = do
  hit <- liftIO $ isHit ray p
  if hit then
    pure $ Board Filled Filled Filled Filled Filled Filled Filled Filled Filled
  else
    pure $ Board Empty Empty Empty Empty Empty Empty Empty Empty Empty


isHit :: RL.Ray -> PositionComponent -> IO Bool
isHit ray (Position p) = do
  let hitInfo = RL.getRayCollisionBox ray $ RL.BoundingBox from to
  -- liftIO $ print "Hello" -- <- uncomment to make this work?
  pure $ RL.raycollision'hit hitInfo > 0
  where from = addVectors p $ Vector3 (-1.5) (-1.5) (-0.05)
        to = addVectors p $ Vector3 1.5 1.5 0.05

```

So this function is WiP, but it tries to detect if the ray shooting from the camera is hitting one of the game boards, and if it does I'm just flagging every cell so that we can see it. Here's the weird thing though: This function only seems to work if you `print` something inside it. I have no idea what this signifies, but after digging down into `h-raylib`'s source code I've found that `getRayCollisionBox` along with lots of other physics functions are **unsafe IO** functions.

I have no experience in FFI or making bindings to C, but while this fact remains true I can't help but wonder if it's the cause. All the other raylib functions I've used I've had to do `liftIO` to access them, and they've all worked really well with no issues this far.

Would it be difficult to make your collision functions also operate within `IO`? At least then if this is still an issue we can conclude its not the bindings?

Alternatively, if you have any suggestions of what the issue could be, please let me know as I'm blocked by this.

Thanks again for the great library!

# Clues

Here's some debugging work I've done:

## Not printing anything

Here's what it looks like if we don't print anything. The boards light up if `hit` is true, which is true when `raycollision'hit hitInfo > 0`. When we don't print anything, all of them are permanently lit even if we don't look at any of them.

![image](https://user-images.githubusercontent.com/8940077/201763914-7933f91a-6cd3-4edf-949f-676e5830bf3c.png)

## Print "hello" or other random things

Uncommenting the comment so that we print `hello` in this function actually fixes it, all three boards are unlit until we look at them:

![image](https://user-images.githubusercontent.com/8940077/201764044-95776648-73bc-4311-a421-e121d9d19c20.png)

![image](https://user-images.githubusercontent.com/8940077/201764065-866d389d-0162-4f19-83de-ce6bab982620.png)

## Printing  `raycollision'hit hitInfo`

This one is an exception - if I print this value, I get the following:
* One board lights up - its `hitInfo` `hit` value is 6749696 - a memory address maybe?
* The second board lights up if I hit it, its `hit` value is `1` if I look at it, and `0` otherwise
* The last board also lights up if I look at it, value is `1` if looked at and `0` otherwise
* Finally, if I look at the first board with the weird number, it's value increases by 1 to 6749697

![image](https://user-images.githubusercontent.com/8940077/201763399-bd44fdf9-c95e-43f5-a365-898f262b0c97.png)

![image](https://user-images.githubusercontent.com/8940077/201763537-6d733258-bc81-4292-9fd3-9a805766a127.png)

![image](https://user-images.githubusercontent.com/8940077/201763125-355a3093-1d80-44c5-9f6b-a5302cec937d.png)

**Comment by Anut-py** [comment]
I will look into this. The functions *should* be okay for `unsafePerformIO`, but if it turns out they aren’t then I’ll implement collision detection math manually in Haskell. I would like to keep `IO` out of these pure functions.

**Comment by Ashe** [comment]
It could be something else entirely, maybe I'm being suspicious of the wrong thing so feel free to correct me if I'm wrong! But this is the first time I've found something like this in Haskell so I'm a bit perplexed!

**Comment by Anut-py** [comment]
Actually, I think it is because `raycollision'hit` uses `CInt` instead of `CBool`, so `raycollision'hit` returns garbage as the first 24 bits. #3 was a similar issue. This should be an easy fix.

**Comment by Ashe** [comment]
Are you sure that `print` is required? Maybe after changing `CInt` to `CBool` things will start working as you expect? 

When you say moving the detection logic into Haskell, wouldn't that be essentially avoiding using Raylib? If that's the case then probably best to just flag it somehow so that people can write their own; I wouldn't say its the responsibility of your repo to re-implement things when it's just meant to be bindings.

**Comment by Anut-py** [comment]
I changed `CInt` to `CBool` in version `4.5.0.5`. I tested it and it seems to be working fine with some example code. If this fixed the problem for you, you can close this issue.

**Comment by Ashe** [comment]
Fixed, thank you for the quick fix and your hard work. Loving the bindings so far! Have a good one!
