### ISSUE TITLE
Pure version of `getScreenToWorld2D` function in rcore

### ISSUE THREAD

**Issue by futu2** [Anut-py/h-raylib#50]
in `Raylib.Core` module, `getScreenToWorld2D  :: Vector2 -> Camera2D -> IO Vector2`
but it is theoretically a pure computation, and pure version is always easier to compose.
Should we add something like `sreenToWorld2D  :: Vector2 -> Camera2D -> Vector2`?
`screenToWorld2D v c = unsafePerformIO $ getScreenToWorld2D v c`

**Comment by Anut-py** [comment]
Published in 5.1.3.0
