### ISSUE TITLE
Expose Raylib.Internal module

### ISSUE THREAD

**Issue by oshyshko** [Anut-py/h-raylib#54]
Could you expose Raylib.Internal module?

Motivation:

I need to have access to internals of WindowResources(..).
Mostly for debugging/introspection purposes:
- to keep an eye counters and spot memory leaks early.
- to have access to actual pointers for investigation purposes.

At the moment, I have a modified local build of h-raylib where I can have the access to it.

Having full access to such hidden layers is important for user developers, so they can know what's going on and are able to investigate and fix things when needed.

Having Raylib.Internal module hidden prevents user developers to spot memory leaks early. Having Raylib.Internal module open contributes to be curious and spot problems early.

I believe it's important for a binding such as h-raylib not to hide or safeguard such crucial bits, especially that they are not internals of raylib itself, but rather a layer built on top of raylib (that can also have bugs and needs to be accessible/investigatable).

**Comment by Anut-py** [comment]
Done in 5.5.0.0
