### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by vitalibarozzi** [Anut-py/h-raylib#58]
Hello. I was wondering where was the binding for the function `SetTraceLogCallback` to specify custom loggers and I couldn't find it. Is there a reason for it not existing, maybe?

**Comment by Anut-py** [comment]
When I first made the bindings I wasn't sure how to bind `SetTraceLogCallback` because it uses varargs, but I think now I can figure out how to do it. I'll give it a try.

**Comment by vitalibarozzi** [comment]
Ah, thank you. :)

**Comment by Anut-py** [comment]
Sorry about the late release, this is now published in h-raylib 5.5.1.0

**Comment by vitalibarozzi** [comment]
Cool, it worked for me. Thanks :D
