### ISSUE TITLE
MacOS build failure

### ISSUE THREAD

**Issue by tebys** [Anut-py/h-raylib#9]
Hi Anut, attached is the output for the mac build, running `cabal run`

<img width="544" alt="image" src="https://user-images.githubusercontent.com/61150722/208161163-e515f9c6-29ef-44d7-a09d-0048cc7e5264.png">

Let me know if I can help any further with info or tests!

Best!

[h-rylb-4.5.0.7-54a0a301.log](https://github.com/Anut-py/h-raylib/files/10248061/h-rylb-4.5.0.7-54a0a301.log)

**Comment by Anut-py** [comment]
This should be fixed in version `4.5.0.8`. Please try it out and if it works, you can close this issue.
